add snyk ignore comment for false positive
it flags the `exec.Command` as a command injection
vulnerability with following error:

```
upstream/main.go:28:9: error[go/CommandInjection]: Unsanitized input from a CLI argument flows into os.exec.Command, where it is used as a shell command. This may result in a Command Injection vulnerability
```

Signed-off-by: Anjan Nath <kaludios@gmail.com>